config/routes.rb
Rails.application.routes.draw do
  

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

	resources :answers
	resources :questions
  resources :quizzes, only: :show do
    collection do
      get :random
    end
  end
  resources :quiz_answers, only: :create
  resources :correctly_answered_questions, only: :destroy


  resources :static_pages, only: :show
  #get 'static_pages/home'
  #get 'static_pages/help'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/question.rb
class Question < ApplicationRecord
  validates :text, length: { minimum: 3 }
  has_many :correctly_answered_questions
  has_many :answers, dependent: :destroy
  validate :question_has_four_answers
  validate :question_has_only_one_correct_answer
  accepts_nested_attributes_for :answers, limit: 4, :reject_if => proc {
  |attributes| attributes['answertext'].blank?
  }  

  def question_has_four_answers
    return if answers.blank?
    if answers.size != 4
      errors.add(:base, "Every question must have 4 answers")
    end 
  end

  def question_has_only_one_correct_answer
    return if answers.blank?
    if answers.select{|a| a.correct == true}.count != 1
      errors.add(:base, "Each question must have one correct answer")
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.paginate(page: params[:page])
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
    4.times do
      @question.answers.build
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:success] = "Your question has been added!"
      redirect_to questions_path
    else
      @n = 0
      @question.answers.each do |ans|
        if !ans.blank?
          @n +=1
        end
      end
      if @n != 4
        (4-@n).times do
          @question.answers.build
        end
      end
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully
                                                  updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_path}
      flash[:success] = "Question deleted"
    end
  end

  private

  def given_answer_params
    return {} if params[:given_answer].blank?
    params.require(:given_answer).permit!
  end

  def answer_correct?
    return false unless find_answer
    @answer.correct?

  end

  def find_answer
    @answer = Answer.find(given_answer_params[:answer_id])
  end

  def question_params
    params.require(:question).permit(:text, answers_attributes: [:id,
                                      :answertext, :correct])
  end
end

app/views/questions/edit.html.erb
<% provide(:title, 'Edit Question') %>

<h1>Edit a question</h1>
<br>
<div class="row", align="center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@question, url: question_path(@question.id), method: :patch) do |f| %>
      <%= render 'shared/question_error_messages' %>
      <%= f.label :text, "Question" %>
      <%= f.text_field :text, class: 'form-control' %>

      <%= f.fields_for :answers do |answer_fields| %>
        <%= answer_fields.label :answertext, "Answer" %>
        <%= answer_fields.text_field :answertext, class: 'form-control' %>

        <%= answer_fields.label :correct, "Is this answer correct?" %>
        <%= answer_fields.check_box :correct %>
      <% end %>
      <br>

      <%= f.submit "Update question", class: "btn btn-primary" %>
    <% end %>

    <%= link_to "Back to the question", question_path(@question) %>
  </div>
</div>

app/views/questions/index.html.erb
<% provide(:title, 'All questions') %>

<%- if !@questions.nil? %>
  <h1> Questions </h1>
  <div class="center">
    <%- if !logged_in? %>
      <p>You must be logged in to access the questions.</p>
      <%= link_to 'Sign up now to start quizzing!', signup_path, class: "btn btn-lg btn-primary" %><br><br><br>
      <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
  <div class="center">
  <%= will_paginate %>
  <%- @questions.each do |q| %>
    <p><%= link_to "#{q.text}", question_path(q.id) if logged_in? %></p>
    <p><%= q.text if !logged_in? %></p>
  <% end %>

  <%= will_paginate %>
</div>
<% else %>
  <h1> We haven't got any questions yet, they're coming soon!</h1>

<% end %>

<div class="center">
  <b><%= link_to "New question", new_question_path if (!current_user.nil? &&current_user.is_admin?) %></b>
</div>

app/views/questions/new.html.erb
<% provide(:title, 'New Question') %>
<h1>New Question</h1>
<br>
<div class="row", align="center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@question, url: questions_path) do |f| %>
      <%= render 'shared/question_error_messages' %>
      <%= f.label :text, "Question" %>
      <%= f.text_field :text, class: 'form-control' %>

        <%= f.fields_for :answers do |answer_fields| %>
          <%= answer_fields.label :answertext, "Answer" %>
          <%= answer_fields.text_field :answertext, class: 'form-control' %>

          <%= answer_fields.label :correct, "Is this answer correct?" %>
          <%= answer_fields.check_box :correct %>
        <% end %>

      <%= f.submit "Add question", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div class="profile_links">
  <%= link_to "All questions", questions_path %>
</div>

app/views/questions/show.html.erb
<% provide(:title, 'Question') %>
<div class="center jumbotron">

  <h1><%= @question.text %></h1>
  <br>

  <%- if !@question.answers.blank? %>
    <% @question.answers.each do |ans| %>
      <button class="btn btn-lg btn-primary"><%= ans.answertext %></button><br><br>
    <% end %>
  <% else %>
    <p>This question has no answers yet, they will be added soon!</p>
    <%= link_to "Add answers", '#' if current_user.is_admin? %><br>
  <% end %>

  <% @question.answers.each do |ans| %>
    <%- if ans.correct? %>
      <button class="btn btn-lg" onclick="myFunction()">Reveal answer</button><br><br>
      <h id="reveal_answer"></h>
      <script>
        function myFunction() {
          document.getElementById("reveal_answer").innerHTML = "<%= ans.answertext%>";
        }
      </script>
    <% end %>
  <% end %>

  <br><br>



  <%- if current_user.is_admin? %>
    <%= link_to "Edit this question", edit_question_path(@question)%><br>
    <%= link_to "Delete this question", question_path(@question), method: :delete %><br>
  <% end %>

  <%= link_to "All questions", questions_path %>

</div>