config/routes.rb
Rails.application.routes.draw do
  

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

	resources :answers
	resources :questions
  resources :quizzes, only: :show do
    collection do
      get :random
    end
  end
  resources :quiz_answers, only: :create
  resources :correctly_answered_questions, only: :destroy


  resources :static_pages, only: :show
  #get 'static_pages/home'
  #get 'static_pages/help'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def show
    @question = Question.find(params[:id])
  end

  def random
    @user = current_user
    @correctly_answered_questions_ids = @user.correctly_answered_questions.collect(&:question_id)
    @question ||= Question.where.not(id: @correctly_answered_questions_ids).order("RANDOM()").first
    if !@question.blank?
      if !@question.answers.blank?
        render :show
      else
        flash[:warning] = "You skipped question #{@question.id}, which has 
                            no answers"
        redirect_to random_quizzes_path
      end
    else
      render :show 
    end
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/show.html.erb
<% provide(:title, 'Quiz') %>

  <div class="center jumbotron">
    <%- if logged_in? %>

      <%- if !@question.blank? %>
        <h1><%= @question.text %></h1>
        <br><br>


        <%- if !@question.answers.blank? %>
          <% @question.answers.each do |ans| %>
            <%= form_for :given_answer, url: quiz_answers_path(@question), method: :post do |form| %>

              <div class="actions">
                <%= form.hidden_field :answer_id, as: :hidden, value: ans.id %>
                <%= form.submit ans.answertext, class: "btn btn-lg btn-primary" %>
              </div><br>
            <% end %>
          <% end %>
        <% else %>
          <p>This question has no answers yet, they will be added soon!</p>
          <%= link_to "Next question", random_quizzes_path %>
        <% end %>
      <% else %>
        <p> You have correctly answered every question! </p>
        <%= link_to "Reset my questions!", correctly_answered_question_path(current_user.correctly_answered_questions.first), method: :delete, class: "btn btn-lg btn-primary" %><br><br>
        <%= link_to "All questions", questions_path, class: "btn btn-lg btn-primary" %>
      <% end %>



      <br><br>
    <% else %> 
      <p> You must be logged in to access the quiz! </p>
      <%= link_to 'Sign up now to start quizzing!', signup_path, class: "btn btn-lg btn-primary" %><br><br><br>
      <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>