config/routes.rb
Rails.application.routes.draw do
  

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

	resources :answers
	resources :questions
  resources :quizzes, only: :show do
    collection do
      get :random
    end
  end
  resources :quiz_answers, only: :create
  resources :correctly_answered_questions, only: :destroy


  resources :static_pages, only: :show
  #get 'static_pages/home'
  #get 'static_pages/help'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    render params[:id]
  end


  def home
  end
  
  def help
  end
end

app/views/static_pages/correct.html.erb
<% provide(:title, 'Quiz') %>
<div class="center jumbotron">
	<p><%= "You answered correctly, you wonderful genius!" %></p><br>
	<%= link_to "Next question", random_quizzes_path,  class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div class="center jumbotron">
<h1>Welcome to the help page!</h1>
<p>Click on an answer to submit it. If you are correct, you will be told this, and you can move on to the next question.</p>
<p>If you are wrong, you must try again!</p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
  <h1>Welcome to the Immersive Labs Cyber Dictionary Quiz</h1>
  <p>Answer the questions to learn all the terms you will need to survive in the cyber industry.</p>
  <%- if logged_in? %>
    <%= link_to 'Click here to start quizzing!', random_quizzes_path, class: "btn btn-lg btn-primary" %><br><br>
  <% else %>
    <%= link_to 'Sign up now to start quizzing!', signup_path, class: "btn btn-lg btn-primary" %><br><br>
  <% end %>
  <%= link_to "All questions", questions_path, class: "btn btn-lg btn-primary" %>
  <h2> Please report any bugs to the interns, we'll be in our corner. </h2>
</div>

app/views/static_pages/incorrect.html.erb
<% provide(:title, 'Quiz') %>
<div class="center jumbotron">
	<p><%= "Incorrect, noob" %></p><br>
	<%= link_to "Try again!", quiz_path(@question),  class: "btn btn-lg btn-primary" %>
</div>