config/routes.rb
Rails.application.routes.draw do
  

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

	resources :answers
	resources :questions
  resources :quizzes, only: :show do
    collection do
      get :random
    end
  end
  resources :quiz_answers, only: :create
  resources :correctly_answered_questions, only: :destroy


  resources :static_pages, only: :show
  #get 'static_pages/home'
  #get 'static_pages/help'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	  <nav>
		  <ul class="footer">
			  <li>This is an <a href="https://immersivelabs.co.uk/">Immersive Labs</a> website</li>
		  </ul>
  	</nav>
  </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Cyber Dictionary", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", static_page_path(:help) %></li>
        <% if logged_in? %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <%- if current_user.is_admin? %>
                <li class="divider"></li>
                <li>
                  <%= link_to "Users", users_path %>
                </li>
              <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>     

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
    	<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
 	  <%= render 'layouts/footer' %>
 	  <!-- <%= debug(params) if Rails.env.development? %> -->
  </body>
</html>